In [1]:
import numpy as np

In [4]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
a.shape

(2, 4)

In [6]:
a[1,3]

7

In [7]:
a[0,2]

2

In [8]:
a[1,2] = 66
a

array([[ 0,  1,  2,  3],
       [ 4,  5, 66,  7]])

In [9]:
a [0]

array([0, 1, 2, 3])

In [10]:
a[1]

array([ 4,  5, 66,  7])

In [11]:
b = np.array([3,5])
b

array([3, 5])

In [12]:
import random

In [13]:
prob = random.random()
print(prob)

0.060170237544493466


In [14]:
number = random.randint(1,6)
print(number)

1


In [17]:
np.random.randint(1,6,(4,6))

array([[2, 4, 1, 4, 5, 4],
       [3, 5, 2, 1, 2, 1],
       [4, 2, 2, 4, 1, 3],
       [3, 2, 5, 3, 3, 3]])